name: Docker Image CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Load test in Docker
      run: docker build -t edi-receiver -f docker/Dockerfile.load.pg . --tag tbt-edi-receiver-test:$(date +%s)
