name: Docker PG Load Test

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker for Test
      run: docker build -t edi-receiver-load-pg -f docker/Dockerfile.load.pg . --tag tbt-edi-receiver-test:$(date +%s)
    - name: Run the Test
      run: docker run --rm -i -t=false edi-receiver-load-pg
